### ISSUE TITLE
Q群执行MC命令QDispathCommand无效

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [XiaMoHuaHuo-CN/CatSero#17]
### 问题描述

QCommandDispath并不能执行相关Q群命令

### 复现方法

1. 使用Q群命令解析器

### 服务端版本

Paper-1.19

### CatSero 版本

1.2-pre

### 服务端日志

```text
无日志显示
```

**Comment by XiaMoHuaHuo-CN** [comment]
[14:15:10] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] [GroupMessage/2064388365] [[SP]风雨阁Storm Pavilion | Minecraft服务器(1165489597)] (647740092) -> !sprco dispatchcmd say
[14:15:24] [DefaultDispatcher-worker-3/INFO]: [MiraiMC] [GroupMessage/2064388365] [[SP]风雨阁Storm Pavilion | Minecraft服务器(1165489597)] (2783999419) -> [mirai:image:{8EED3945-867B-F00F-D43C-B5E851832096}.jpg]
[14:15:26] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] [GroupMessage/2064388365] [[SP]风雨阁Storm Pavilion | Minecraft服务器(1165489597)] 单挑眞白かのん(2549619802) -> !sprco dispatchcmd say+Hello
[14:15:26] [DefaultDispatcher-worker-1/ERROR]: Thread DefaultDispatcher-worker-1 failed main thread check: command dispatch
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:882) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:959) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at moe.xmcn.catsero.events.listeners.QDispathCommand.OnQQGroupMessage.onMiraiGroupMessageEvent(OnQQGroupMessage.java:41) ~[CatSero-1.2-pre1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor84.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:106) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43) ~[MiraiMC-Bukkit.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
[14:15:26] [DefaultDispatcher-worker-1/ERROR]: Could not pass event MiraiGroupMessageEvent to CatSero v1.2-pre1
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:882) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:959) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at moe.xmcn.catsero.events.listeners.QDispathCommand.OnQQGroupMessage.onMiraiGroupMessageEvent(OnQQGroupMessage.java:41) ~[CatSero-1.2-pre1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor84.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:106) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43) ~[MiraiMC-Bukkit.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]

**Comment by XiaMoHuaHuo-CN** [comment]
由于未知原因 数据读取值不正常

**Comment by XiaMoHuaHuo-CN** [comment]
> 由于未知原因 数据读取值不正常

鬼 在异步任务执行 我是大聪明

**Comment by XiaMoHuaHuo-CN** [comment]
https://github.com/XiaMoHuaHuo-CN/CatSero/actions/runs/2908282992
