### ISSUE TITLE
QQ群执行Minecraft命令时日志无法读取

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [XiaMoHuaHuo-CN/CatSero#34]
### 问题描述

如题

### 复现方法

1. 使用此功能

### 服务端版本

Purpur-1.19.2

### CatSero 版本

2.0-beta-4

### 服务端日志

```text
[18:51:08] [ServerMain/INFO]: Building unoptimized datafixer
[18:51:10] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:51:13] [ServerMain/INFO]: Loaded 7 recipes
[18:51:15] [Server thread/INFO]: Starting minecraft server version 1.19.2
[18:51:15] [Server thread/WARN]: ****************************
[18:51:15] [Server thread/WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[18:51:15] [Server thread/WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[18:51:15] [Server thread/WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[18:51:15] [Server thread/WARN]: ****************************
[18:51:15] [Server thread/INFO]: Loading properties
[18:51:15] [Server thread/INFO]: This server is running Purpur version git-Purpur-1762 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 39e30d6 on HEAD)
[18:51:16] [Server thread/INFO]: Server Ping Player Sample Count: 12
[18:51:16] [Server thread/INFO]: Using 4 threads for Netty based IO
[18:51:16] [Server thread/WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[18:51:16] [Server thread/WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[18:51:16] [Server thread/WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[18:51:16] [Server thread/WARN]: [Pufferfish] Debug: Java: 17.0.4, test run: true
[18:51:16] [Server thread/INFO]: Default game type: SURVIVAL
[18:51:16] [Server thread/INFO]: Generating keypair
[18:51:17] [Server thread/INFO]: Starting Minecraft server on *:8620
[18:51:17] [Server thread/INFO]: Using epoll channel type
[18:51:17] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[18:51:17] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[18:51:18] [Server thread/ERROR]: Purpur: Failed to download and install spark plugin
[18:51:18] [Server thread/WARN]: java.net.SocketException: Connection reset
[18:51:18] [Server thread/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
[18:51:18] [Server thread/WARN]: 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1505)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1420)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[18:51:18] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[18:51:18] [Server thread/WARN]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[18:51:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:434)
[18:51:18] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[18:51:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1141)
[18:51:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[18:51:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[18:51:19] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib-common:1.5.10
[18:51:19] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib:1.5.10
[18:51:19] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.jetbrains:annotations:13.0
[18:51:19] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.10
[18:51:19] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.10
[18:51:20] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.openjdk.nashorn:nashorn-core:15.3
[18:51:20] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.ow2.asm:asm-commons:7.3.1
[18:51:20] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.ow2.asm:asm-tree:7.3.1
[18:51:20] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.ow2.asm:asm:7.3.1
[18:51:20] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.ow2.asm:asm-util:7.3.1
[18:51:20] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library com.typesafe:config:1.4.1
[18:51:20] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library com.electronwill.night-config:core:3.6.5
[18:51:20] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library com.electronwill.night-config:toml:3.6.5
[18:51:20] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library com.electronwill.night-config:json:3.6.5
[18:51:20] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library com.electronwill.night-config:hocon:3.6.5
[18:51:20] [ForkJoinPool.commonPool-worker-1/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.apache.commons:commons-jexl3:3.2.1
[18:51:21] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library com.zaxxer:HikariCP:4.0.3
[18:51:21] [Server thread/INFO]: [TrChat-2.0.0-PRE-33.jar] Loading library org.slf4j:slf4j-api:2.0.3
[18:51:22] [Server thread/WARN]: [TrChat] General.Mention-All.Format not found in function.yml
[18:51:22] [Server thread/INFO]: [MiraiMC] Loading MiraiMC v1.7
[18:51:24] [Server thread/INFO]: [MiraiMC] Verifying mirai-core-all-2.11.1.jar
[18:51:25] [Server thread/INFO]: [MiraiMC] Loading library plugins/MiraiMC/MiraiBot/libs/mirai-core-all-2.11.1.jar
[18:51:25] [Server thread/INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.2
[18:51:25] [Server thread/INFO]: [TrChat] Loading TrChat v2.0.0-PRE-33
[18:51:25] [Server thread/INFO]: 
[18:51:25] [Server thread/INFO]: 正在加载 TrChat... 1.19.2-R0.1-SNAPSHOT
[18:51:25] [Server thread/INFO]: 
[18:51:25] [Server thread/INFO]: [CatSero] Loading CatSero v2.0-beta-3
[18:51:25] [Server thread/INFO]: [CatSero] [Loader] 检查运行环境
[18:51:25] [Server thread/INFO]: [CatSero] [Loader] 依赖装载情况:
[18:51:25] [Server thread/INFO]: [CatSero] [Loader] - MiraiMC => true
[18:51:25] [Server thread/INFO]: [CatSero] [Loader] - PlaceholderAPI => true
[18:51:25] [Server thread/INFO]: [CatSero] [Loader] - TrChat => true
[18:51:25] [Server thread/INFO]: [CatSero] [Loader] 
[18:51:25] [Server thread/INFO]: [CatSero] [Loader] 服务器版本: 1.19.2-R0.1-SNAPSHOT
[18:51:25] [Server thread/INFO]: [CatSero] [Loader] 保存插件文件
[18:51:25] [Server thread/INFO]: [CatSero] [Loader] 成功保存插件文件
[18:51:25] [Server thread/INFO]: [CatSero] [Loader] 加载bStats统计
[18:51:25] [Server thread/INFO]: [CatSero] [Loader] 成功加载bStats统计
[18:51:25] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:51:25] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[18:51:25] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[18:51:25] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[18:51:25] [Server thread/WARN]: You will not be offered any support as long as the server allows offline-mode players to join.
[18:51:25] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[18:51:25] [Server thread/INFO]: Preparing level "world"
[18:51:45] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[18:51:46] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:46] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:46] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:46] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:47] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:47] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:48] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:48] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:49] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:49] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:49] [Server thread/INFO]: Time elapsed: 4704 ms
[18:51:49] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[18:51:50] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:50] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:50] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:51] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:52] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:52] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:52] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:53] [Server thread/INFO]: Time elapsed: 3290 ms
[18:51:53] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[18:51:53] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:53] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:54] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:54] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:55] [Server thread/INFO]: Preparing spawn area: 0%
[18:51:55] [Server thread/INFO]: Time elapsed: 2056 ms
[18:51:55] [Server thread/INFO]: [MiraiMC] Enabling MiraiMC v1.7
[18:51:55] [Server thread/INFO]: [MiraiMC] Mirai working dir: default
[18:51:55] [Server thread/INFO]: [MiraiMC] Starting Mirai-Events listener.
[18:51:55] [Server thread/INFO]: [MiraiMC] Loading auto-login file.
[18:51:55] [Server thread/INFO]: [MiraiMC] Registering commands.
[18:51:55] [Server thread/INFO]: [MiraiMC] Registering events.
[18:51:55] [Server thread/INFO]: [MiraiMC] Initializing SQLite database.
[18:51:55] [Server thread/INFO]: [MiraiMC] Initializing bStats metrics.
[18:51:55] [Server thread/WARN]: [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[18:51:55] [Server thread/WARN]: [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[18:51:55] [Server thread/INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[18:51:55] [Server thread/INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.2
[18:51:55] [Server thread/INFO]: [PlaceholderAPI] Fetching available expansion information...
[18:51:55] [Server thread/INFO]: [TrChat] Enabling TrChat v2.0.0-PRE-33
[18:51:55] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: trchat [2.0.0-PRE-33]
[18:51:56] [Server thread/INFO]: [com.zaxxer.hikari_4_0_3.HikariDataSource] HikariPool-1 - Starting...
[18:51:56] [Server thread/INFO]: [com.zaxxer.hikari_4_0_3.HikariDataSource] HikariPool-1 - Start completed.
[18:51:56] [Server thread/INFO]: [TrChat] 当前无跨服支持.
[18:51:56] [Server thread/INFO]: [TrChat] 聊天 | 成功载入 4 个聊天频道... [18 Ms]
[18:51:56] [Server thread/INFO]: [TrChat] 聊天 | 成功载入 12 个聊天功能... [2 Ms]
[18:51:56] [Server thread/INFO]: [TrChat] 过滤器 | 已载入本地敏感词库总计 3 个.
[18:51:56] [Server thread/INFO]: [TrChat] 信息 | 加载完毕. TrChat v2.0.0-PRE-33 现已启用, 敬请使用.
[18:51:56] [Server thread/INFO]: [CatSero] Enabling CatSero v2.0-beta-3
[18:51:56] [Server thread/INFO]: [CatSero] [Loader] 注册监听器
[18:51:56] [Server thread/INFO]: [CatSero] [Loader] 成功注册监听器
[18:51:56] [Server thread/INFO]: [CatSero] [Loader] 启动TPS计算器
[18:51:56] [Server thread/INFO]: [CatSero] [Loader] 成功启动TPS计算器
[18:51:56] [Server thread/INFO]: [CatSero] [Loader] 加载完毕，启用插件
[18:51:56] [Server thread/INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[18:51:56] [Server thread/INFO]: Running delayed init tasks
[18:51:56] [Craft Scheduler Thread - 4 - MiraiMC/INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[18:51:56] [Craft Scheduler Thread - 5 - MiraiMC/INFO]: [MiraiMC] Checking update...
[18:51:56] [Craft Scheduler Thread - 5 - MiraiMC/INFO]: [MiraiMC] You are using the latest version!
[18:51:56] [Craft Scheduler Thread - 5 - TrChat/INFO]: [PlaceholderAPI] Fetching available expansion information...
[18:51:56] [Craft Scheduler Thread - 4 - MiraiMC/INFO]: [MiraiMC] [AutoLogin] Auto login bot account: 1792966170 Protocol: ANDROID_PHONE
[18:51:56] [Craft Scheduler Thread - 4 - MiraiMC/INFO]: [MiraiMC] 登录新的机器人账号: 1792966170, 协议: ANDROID_PHONE
[18:51:56] [Craft Scheduler Thread - 7 - TrChat/INFO]: [TrChat] Error occurred while catching cloud thesaurus.
[18:51:56] [Craft Scheduler Thread - 7 - TrChat/INFO]:          拒绝连接
[18:51:56] [Craft Scheduler Thread - 7 - TrChat/INFO]: [TrChat] 无法从云端更新敏感词库......
[18:51:56] [Server thread/WARN]: [PlaceholderAPI] Cannot load expansion multiverse due to a missing plugin: Multiverse-Core
[18:51:56] [Server thread/WARN]: [PlaceholderAPI] Cannot load expansion vault due to a missing plugin: Vault
[18:51:56] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: player [2.0.3]
[18:51:56] [Server thread/INFO]: 1 placeholder hook(s) registered!
[18:51:56] [Server thread/INFO]: Done (40.968s)! For help, type "help"
[18:51:58] [Craft Scheduler Thread - 9 - TrChat/INFO]: [TrChat] 你正在运行最新版的 TrChat.
[18:51:58] [Craft Scheduler Thread - 9 - MiraiMC/INFO]: [MiraiMC] ========== [ MiraiMC 公告版 ] ==========
[18:51:58] [Craft Scheduler Thread - 9 - MiraiMC/INFO]: [MiraiMC] 腾讯已开始使用主动发送验证码的设备锁验证形式。
[18:51:58] [Craft Scheduler Thread - 9 - MiraiMC/INFO]: [MiraiMC] 如有用户遇到此类验证码或发现无论如何都无法通过设备锁验证，
[18:51:58] [Craft Scheduler Thread - 9 - MiraiMC/INFO]: [MiraiMC] 请前往GitHub开新issue，我将尽快提供支持。
[18:51:58] [Craft Scheduler Thread - 9 - MiraiMC/INFO]: [MiraiMC] =======================================
[18:51:59] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Server list: 36.155.207.223:443, 111.31.200.210:14000, 120.232.27.24:80, 120.232.31.164:80, 36.155.213.212:80, 111.30.187.201:80, 120.232.69.203:8080, msfwifi.3g.qq.com:8080, 111.30.187.227:80.
[18:52:00] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Loaded account secrets from local cache.
[18:52:00] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] ECDH key is valid.
[18:52:01] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Saved account secrets to local cache for fast login.
[18:52:01] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Login successful.
[18:52:01] [nioEventLoopGroup-2-3/INFO]: [MiraiMC] Server time updated, serverTime: 1664621521, diff: 0ms=0.0s
[18:52:01] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Syncing friend message history...
[18:52:01] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Start loading stranger list...
[18:52:01] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Start loading friend list...
[18:52:01] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Successfully loaded stranger list: 0 in total
[18:52:01] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Syncing friend message history: Success.
[18:52:02] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] No OtherClient online.
[18:52:02] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Start loading group list...
[18:52:02] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Successfully loaded friend list: 5 in total
[18:52:02] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Successfully loaded group list: 1 in total.
[18:52:02] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Bot login successful.
[18:52:02] [Craft Scheduler Thread - 4 - MiraiMC/INFO]: [MiraiMC] 小さい月(1792966170) 登录成功
[18:52:02] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Scheduled key refresh in 23h 55min 0.0s.
[18:52:02] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Scheduled refresh login session in 19d 23h 55min 0.0s.
[18:52:07] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] [GroupMessage/1792966170] [[SP]风雨阁Storm Pavilion | Minecraft服务器(1165489597)] 单挑眞白かのん(2549619802) -> !catsero cmd catsero
[18:52:07] [DefaultDispatcher-worker-1/INFO]: [CatSero] null
[18:52:07] [DefaultDispatcher-worker-1/WARN]: [CatSero] [Catch] 捕获到一个错误
[18:52:07] [DefaultDispatcher-worker-1/WARN]: [CatSero] [Catch] 错误类型: java.lang.NullPointerException
[18:52:07] [DefaultDispatcher-worker-1/WARN]: [CatSero] [Catch] 捕获消息: Parameter specified as non-null is null: method net.mamoe.mirai.contact.NormalMember.sendMessage, parameter message
[18:52:07] [DefaultDispatcher-worker-1/WARN]: [CatSero] [Catch] 详细信息: [MiraiMC-Bukkit.jar//net.mamoe.mirai.contact.NormalMember.sendMessage(NormalMember.kt), MiraiMC-Bukkit.jar//me.dreamvoid.miraimc.api.bot.group.MiraiNormalMember.sendMessage(MiraiNormalMember.java:76), CatSero.jar//moe.xmcn.catsero.v2.utils.Env$AMiraiMC.sendMiraiGroupMemberMessage(Env.java:94), CatSero.jar//moe.xmcn.catsero.v2.listeners.DispatchCommand.OnMiraiGroupMessageEvent.onMiraiGroupMessageEvent(OnMiraiGroupMessageEvent.java:42), com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor14.execute(Unknown Source), org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75), co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76), org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70), org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678), MiraiMC-Bukkit.jar//me.dreamvoid.miraimc.bukkit.MiraiEvent.lambda$startListenEvent$8(MiraiEvent.java:106), MiraiMC-Bukkit.jar//net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574), MiraiMC-Bukkit.jar//net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:574), MiraiMC-Bukkit.jar//kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51), MiraiMC-Bukkit.jar//kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1), MiraiMC-Bukkit.jar//kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43), MiraiMC-Bukkit.jar//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33), MiraiMC-Bukkit.jar//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106), MiraiMC-Bukkit.jar//kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42), MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95), MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570), MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749), MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677), MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)]
[18:52:07] [Server thread/INFO]: [CatSero] $%{CatSignStart@8a2220bc-c0c9-4840-875c-0fcf7c86f70a}%$
[18:52:07] [Server thread/INFO]: CatSero by XiaMoHuaHuo_CN
[18:52:07] [Server thread/INFO]: [CatSero] $%{CatSignEnd@8a2220bc-c0c9-4840-875c-0fcf7c86f70a}%$
[18:53:12] [Server thread/INFO]: Stopping the server
[18:53:12] [Server thread/INFO]: Stopping server
[18:53:12] [Server thread/INFO]: [CatSero] Disabling CatSero v2.0-beta-3
[18:53:12] [Server thread/INFO]: [CatSero] [Loader] 卸载CatSero插件，感谢您使用CatSero
[18:53:12] [Server thread/INFO]: [TrChat] Disabling TrChat v2.0.0-PRE-33
[18:53:12] [Server thread/INFO]: [com.zaxxer.hikari_4_0_3.HikariDataSource] HikariPool-1 - Shutdown initiated...
[18:53:12] [Server thread/INFO]: [com.zaxxer.hikari_4_0_3.HikariDataSource] HikariPool-1 - Shutdown completed.
[18:53:12] [Server thread/INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.11.2
[18:53:12] [Server thread/INFO]: [MiraiMC] Disabling MiraiMC v1.7
[18:53:12] [Server thread/INFO]: [MiraiMC] Stopping bot event listener.
[18:53:12] [Server thread/INFO]: [MiraiMC] Closing all bots
[18:53:12] [Server thread/INFO]: [MiraiMC] Bot cancelled: Job was cancelled
[18:53:12] [Server thread/INFO]: [MiraiMC] Closing SQLite database.
[18:53:12] [Server thread/INFO]: [MiraiMC] All tasks done. Thanks for use MiraiMC!
[18:53:12] [Server thread/INFO]: Saving players
[18:53:13] [Server thread/INFO]: Saving worlds
[18:53:19] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[18:53:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[18:53:20] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[18:53:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[18:53:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:53:20] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:53:20] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[18:53:22] [Server thread/INFO]: Flushing Chunk IO
[18:53:22] [Server thread/INFO]: Closing Thread Pool
[18:53:22] [Server thread/INFO]: Closing Server
```

### 额外说明

已知因日志读取无法匹配内容导致

**Comment by XiaMoHuaHuo-CN** [comment]
不再读取日志，Close
